name: Aradium
version: '${project.version}'
main: pl.nauka.aradium.AradiumPlugin
api-version: 1.19
commands:
  magicitem:
    description: Nadaje magiczne przedmioty i zbroje graczom
    usage: /magicitem <gracz> <typ> <poziom>
    permission: aradium.admin
  oreregion:
    description: Narzedzie do oznaczania strefy rud (odnawialnych)
    usage: /oreregion <ruda> <min|max>
    permission: aradium.admin
permissions:
  aradium.admin:
    description: Dostęp do komend administracyjnych pluginu
    default: op